ObrazovneUstanove/ObrazovneUstanove.UI/Controllers/KorisnikController.cs
using System.Web.Mvc;
using ObrazovneUstanove.Service;
using System.Linq;
using ObrazovneUstanove.UI.Models;
using System.Linq.Dynamic;
using ObrazovneUstanove.Domain;
using ObrazovneUstanove.UI.Custom.Extensions;
using System;

namespace ObrazovneUstanove.UI.Controllers
{
    public class KorisnikController : Controller
    {
        private readonly IServiceContainer ServiceContainer;

        public KorisnikController(IServiceContainer ServiceContainer)
        {
            this.ServiceContainer = ServiceContainer;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult List(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            var data = ServiceContainer.KorisnikService.GetAll();

            var list = data.Select(o => new KorisnikViewModel
            {
                KorisnikId = o.KorisnikId,
                Ime = o.Ime,
                Prezime = o.Prezime,
                ImeJednogRoditelja = o.ImeJednogRoditelja,
                Jmb = o.Jmb,
                Pol = o.Pol,
                DatumRodjenja = o.DatumRodjenja,
                MjestoRodjenjaOpstinaId = o.MjestoRodjenjaOpstinaId,
                PrebivalisteNaseljenoMjestoId = o.PrebivalisteNaseljenoMjestoId,
                StrucnaSpremaId = o.StrucnaSpremaId,
                Zanimanje = o.Zanimanje
            }).OrderBy(jtSorting).Skip(jtStartIndex).Take(jtPageSize).ToList();

            return Json(new { Result = "OK", Records = list, TotalRecordCount = data.Count() });
        }

        [HttpPost]
        public JsonResult Create(KorisnikViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { Result = "ERROR", Message = ModelState.UserFriendlyErrors() });
            }

            var model = new Korisnik
            {
                Ime = viewModel.Ime,
                Prezime = viewModel.Prezime,
                ImeJednogRoditelja = viewModel.ImeJednogRoditelja,
                Jmb = viewModel.Jmb,
                Pol = viewModel.Pol,
                DatumRodjenja = viewModel.DatumRodjenja,
                MjestoRodjenjaOpstinaId = viewModel.MjestoRodjenjaOpstinaId,
                PrebivalisteNaseljenoMjestoId = viewModel.PrebivalisteNaseljenoMjestoId,
                StrucnaSpremaId = viewModel.StrucnaSpremaId,
                Zanimanje = viewModel.Zanimanje
            };

            viewModel.KorisnikId = ServiceContainer.KorisnikService.AddGetId(model);

            return Json(new { Result = "OK", Record = viewModel });
        }

        [HttpPost]
        public JsonResult Update(KorisnikViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { Result = "ERROR", Message = ModelState.UserFriendlyErrors() });
            }

            var model = ServiceContainer.KorisnikService.Get(viewModel.KorisnikId);

            if (model != null)
            {
                model.Ime = viewModel.Ime;
                model.Prezime = viewModel.Prezime;
                model.ImeJednogRoditelja = viewModel.ImeJednogRoditelja;
                model.Jmb = viewModel.Jmb;
                model.Pol = viewModel.Pol;
                model.DatumRodjenja = viewModel.DatumRodjenja;
                model.MjestoRodjenjaOpstinaId = viewModel.MjestoRodjenjaOpstinaId;
                model.PrebivalisteNaseljenoMjestoId = viewModel.PrebivalisteNaseljenoMjestoId;
                model.StrucnaSpremaId = viewModel.StrucnaSpremaId;
                model.Zanimanje = viewModel.Zanimanje;

                ServiceContainer.KorisnikService.Update(model);
            }

            return Json(new { Result = "OK", Record = viewModel });
        }

        [HttpPost]
        public JsonResult Delete(int KorisnikId)
        {
            try
            {
                ServiceContainer.KorisnikService.Delete(KorisnikId);
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

ObrazovneUstanove/ObrazovneUstanove.UI/Views/Shared/_Footer.cshtml
<footer>
    <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
</footer>

ObrazovneUstanove/ObrazovneUstanove.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">

            <!-- #section:basics/sidebar -->
            @Html.Partial("_Sidebar")
            <!-- /section:basics/sidebar -->

            <!-- top navigation -->
            @Html.Partial("_Navbar")
            <!-- /top navigation -->


            <div class="right_col" role="main">
                <div class="row">
                    <div class="col-xs-12">
                        @RenderBody()
                    </div>               
                </div>                
            </div>
            <div id="dialog-confirm" class="ui-dialog-content ui-widget-content" style="width: auto; min-height: 28px; max-height: none; height: auto; display: none;">
                <div class="alert alert-info bigger-110">Izvršili ste izmjene podataka na stranici. Da li želite da te izmjene budu sačuvane? </div>
            </div>

            <!-- footer content -->
            @Html.Partial("_Footer")
            <!-- /footer content -->

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jTable")
    @RenderSection("scripts", required: false)
</body>
</html>

ObrazovneUstanove/ObrazovneUstanove.UI/Views/Shared/_Navbar.cshtml
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        @*<img src="images/img.jpg" alt="">*@John Doe
                        <span class="fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">Help</a></li>
                        <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        @*<li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>*@
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

ObrazovneUstanove/ObrazovneUstanove.UI/Views/Shared/_Sidebar.cshtml
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentellela Alela!</span></a>
        </div>
        <div class="clearfix"></div>
        <!-- menu profile quick info -->
        <div class="profile">
            <div class="profile_pic">
                @*<img src="images/img.jpg" alt="..." class="img-circle profile_img">*@
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <br />
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="index.html">Dashboard</a></li>
                            <li><a href="index2.html">Dashboard2</a></li>
                            <li><a href="index3.html">Dashboard3</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-edit"></i> Admin <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="@Url.Action("Index", "Korisnik")">Korisnik</a></li>
                            <li><a href="form_advanced.html">Advanced Components</a></li>
                            <li><a href="form_validation.html">Form Validation</a></li>
                            <li><a href="form_wizards.html">Form Wizard</a></li>
                            <li><a href="form_upload.html">Form Upload</a></li>
                            <li><a href="form_buttons.html">Form Buttons</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="general_elements.html">General Elements</a></li>
                            <li><a href="media_gallery.html">Media Gallery</a></li>
                            <li><a href="typography.html">Typography</a></li>
                            <li><a href="icons.html">Icons</a></li>
                            <li><a href="glyphicons.html">Glyphicons</a></li>
                            <li><a href="widgets.html">Widgets</a></li>
                            <li><a href="invoice.html">Invoice</a></li>
                            <li><a href="inbox.html">Inbox</a></li>
                            <li><a href="calendar.html">Calendar</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="tables.html">Tables</a></li>
                            <li><a href="tables_dynamic.html">Table Dynamic</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="chartjs.html">Chart JS</a></li>
                            <li><a href="chartjs2.html">Chart JS2</a></li>
                            <li><a href="morisjs.html">Moris JS</a></li>
                            <li><a href="echarts.html">ECharts</a></li>
                            <li><a href="other_charts.html">Other Charts</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                            <li><a href="fixed_footer.html">Fixed Footer</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="menu_section">
                <h3>Live On</h3>
                <ul class="nav side-menu">
                    <li>
                        <a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="e_commerce.html">E-commerce</a></li>
                            <li><a href="projects.html">Projects</a></li>
                            <li><a href="project_detail.html">Project Detail</a></li>
                            <li><a href="contacts.html">Contacts</a></li>
                            <li><a href="profile.html">Profile</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="page_403.html">403 Error</a></li>
                            <li><a href="page_404.html">404 Error</a></li>
                            <li><a href="page_500.html">500 Error</a></li>
                            <li><a href="plain_page.html">Plain Page</a></li>
                            <li><a href="login.html">Login Page</a></li>
                            <li><a href="pricing_tables.html">Pricing Tables</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="#level1_1">Level One</a>
                            <li>
                                <a>Level One<span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li class="sub_menu">
                                        <a href="level2.html">Level Two</a>
                                    </li>
                                    <li>
                                        <a href="#level2_1">Level Two</a>
                                    </li>
                                    <li>
                                        <a href="#level2_2">Level Two</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#level1_2">Level One</a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->
        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>